[package]
name = "node-health"
version = "0.3.0"
edition = "2021"
default-run = "node-health"

# Here to support the Docker build.
[[bin]]
name = "node-health"
path = "src/main.rs"

[dependencies]
anyhow = { version = "1.0.101", default-features = false, features = [
	"backtrace",
	"std",
] }
axum = { version = "0.6.20", default-features = false, features = [
	"json",
	"tokio",
	"http1",
] }
dotenvy = "0.15.7"
reqwest = { version = "0.11.27", default-features = false, features = ["json"] }
serde = { version = "1.0.228", default-features = false, features = [
	"derive",
	"std",
] }
serde_json = { version = "1.0.149", default-features = false, features = [
	"std",
] }
tokio = { version = "1.49.0", default-features = false, features = [
	"macros",
	"rt-multi-thread",
	"rt",
	"time",
	"signal",
] }
tracing = { version = "0.1.44", default-features = false, features = ["std"] }
tracing-subscriber = { version = "0.3.22", default-features = false, features = [
	"alloc",
	"ansi",
	"env-filter",
	"json",
] }

[dev-dependencies]
mockito = "1.7.2"
